<?php

$programmingLanguages = [

    "php" => [
        "name" => "PHP (Hypertext Preprocessor)",
        "type" => "Backend / Server-side",
        "first_release" => "1995",
        "creator" => "Rasmus Lerdorf",
        "paradigm" => "Procedural, Object-Oriented",
        "typing" => "Dynamically Typed",
        "execution" => "Interpreted",
        "file_extension" => ".php",
        "popular_frameworks" => "Laravel, Symfony, CodeIgniter",
        "used_for" => "Web development, APIs, CMS",
        "why_use" => "Easy to learn, huge ecosystem, strong web support",
        "strengths" => "Fast development, cheap hosting, large community",
        "weaknesses" => "Inconsistent design, less modern compared to others",
        "database_support" => "MySQL, PostgreSQL, SQLite",
        "job_market" => "High demand for web/backend",
        "learning_curve" => "Easy to Medium",
        "example_project" => "Blog system, REST API, E-commerce",
    ],

    "javascript" => [
        "name" => "JavaScript",
        "type" => "Frontend + Backend",
        "first_release" => "1995",
        "creator" => "Brendan Eich",
        "paradigm" => "Event-driven, Functional, OOP",
        "typing" => "Dynamically Typed",
        "execution" => "Interpreted",
        "file_extension" => ".js",
        "popular_frameworks" => "React, Node.js, Express",
        "used_for" => "Web apps, APIs, real-time apps",
        "why_use" => "Runs everywhere (browser + server)",
        "strengths" => "Huge ecosystem, async handling",
        "weaknesses" => "Callback hell, inconsistent behavior",
        "database_support" => "MongoDB, MySQL, Firebase",
        "job_market" => "Very High demand",
        "learning_curve" => "Medium",
        "example_project" => "Chat app, dashboard, API server",
    ],

    "python" => [
        "name" => "Python",
        "type" => "General-purpose",
        "first_release" => "1991",
        "creator" => "Guido van Rossum",
        "paradigm" => "Object-Oriented, Functional",
        "typing" => "Dynamically Typed",
        "execution" => "Interpreted",
        "file_extension" => ".py",
        "popular_frameworks" => "Django, Flask, FastAPI",
        "used_for" => "AI, backend, automation",
        "why_use" => "Simple syntax, powerful libraries",
        "strengths" => "Readable, huge ecosystem",
        "weaknesses" => "Slower than compiled languages",
        "database_support" => "PostgreSQL, MySQL, SQLite",
        "job_market" => "Very High demand",
        "learning_curve" => "Easy",
        "example_project" => "AI chatbot, API, automation scripts",
    ],

    "java" => [
        "name" => "Java",
        "type" => "General-purpose",
        "first_release" => "1995",
        "creator" => "James Gosling",
        "paradigm" => "Object-Oriented",
        "typing" => "Statically Typed",
        "execution" => "Compiled (JVM)",
        "file_extension" => ".java",
        "popular_frameworks" => "Spring Boot, Hibernate",
        "used_for" => "Enterprise apps, Android",
        "why_use" => "Stable, scalable, widely used",
        "strengths" => "Performance, security",
        "weaknesses" => "Verbose syntax",
        "database_support" => "MySQL, Oracle, PostgreSQL",
        "job_market" => "High demand",
        "learning_curve" => "Medium to Hard",
        "example_project" => "Banking system, Android app",
    ],

    "csharp" => [
        "name" => "C#",
        "type" => "General-purpose",
        "first_release" => "2000",
        "creator" => "Microsoft",
        "paradigm" => "Object-Oriented",
        "typing" => "Statically Typed",
        "execution" => "Compiled (.NET)",
        "file_extension" => ".cs",
        "popular_frameworks" => ".NET, ASP.NET",
        "used_for" => "Desktop, backend, games",
        "why_use" => "Strong Microsoft ecosystem",
        "strengths" => "Performance, tooling",
        "weaknesses" => "Less flexible outside .NET",
        "database_support" => "SQL Server, MySQL",
        "job_market" => "High demand",
        "learning_curve" => "Medium",
        "example_project" => "Web API, Unity game",
    ],

    "cpp" => [
        "name" => "C++",
        "type" => "System programming",
        "first_release" => "1985",
        "creator" => "Bjarne Stroustrup",
        "paradigm" => "Procedural, OOP",
        "typing" => "Statically Typed",
        "execution" => "Compiled",
        "file_extension" => ".cpp",
        "popular_frameworks" => "Qt",
        "used_for" => "Game engines, OS, high performance apps",
        "why_use" => "Very fast, low-level control",
        "strengths" => "Performance",
        "weaknesses" => "Complex syntax",
        "database_support" => "SQLite, MySQL",
        "job_market" => "Moderate demand",
        "learning_curve" => "Hard",
        "example_project" => "Game engine, system tool",
    ],

    "go" => [
        "name" => "Go (Golang)",
        "type" => "Backend / System",
        "first_release" => "2009",
        "creator" => "Google",
        "paradigm" => "Concurrent, Procedural",
        "typing" => "Statically Typed",
        "execution" => "Compiled",
        "file_extension" => ".go",
        "popular_frameworks" => "Gin, Echo",
        "used_for" => "APIs, cloud services",
        "why_use" => "Fast, simple concurrency",
        "strengths" => "Performance, simplicity",
        "weaknesses" => "Less flexible OOP",
        "database_support" => "PostgreSQL, MySQL",
        "job_market" => "Growing fast",
        "learning_curve" => "Medium",
        "example_project" => "API server, microservices",
    ],

    "rust" => [
        "name" => "Rust",
        "type" => "System programming",
        "first_release" => "2010",
        "creator" => "Mozilla",
        "paradigm" => "Functional, OOP",
        "typing" => "Statically Typed",
        "execution" => "Compiled",
        "file_extension" => ".rs",
        "popular_frameworks" => "Actix, Rocket",
        "used_for" => "System, backend",
        "why_use" => "Memory safety without GC",
        "strengths" => "Safety + performance",
        "weaknesses" => "Hard to learn",
        "database_support" => "PostgreSQL",
        "job_market" => "Growing",
        "learning_curve" => "Hard",
        "example_project" => "High-performance API",
    ],

    "swift" => [
        "name" => "Swift",
        "type" => "Mobile development",
        "first_release" => "2014",
        "creator" => "Apple",
        "paradigm" => "OOP, Functional",
        "typing" => "Statically Typed",
        "execution" => "Compiled",
        "file_extension" => ".swift",
        "popular_frameworks" => "SwiftUI",
        "used_for" => "iOS apps",
        "why_use" => "Modern Apple development",
        "strengths" => "Fast, safe",
        "weaknesses" => "Apple-only",
        "database_support" => "CoreData, SQLite",
        "job_market" => "High for iOS",
        "learning_curve" => "Medium",
        "example_project" => "iPhone app",
    ],

    "kotlin" => [
        "name" => "Kotlin",
        "type" => "Mobile + Backend",
        "first_release" => "2011",
        "creator" => "JetBrains",
        "paradigm" => "OOP, Functional",
        "typing" => "Statically Typed",
        "execution" => "JVM",
        "file_extension" => ".kt",
        "popular_frameworks" => "Ktor, Spring",
        "used_for" => "Android, backend",
        "why_use" => "Better than Java",
        "strengths" => "Concise, modern",
        "weaknesses" => "Smaller ecosystem",
        "database_support" => "MySQL, PostgreSQL",
        "job_market" => "High for Android",
        "learning_curve" => "Medium",
        "example_project" => "Android app",
    ],

    "sql" => [
        "name" => "SQL (Structured Query Language)",
        "type" => "Database",
        "first_release" => "1974",
        "creator" => "IBM",
        "paradigm" => "Declarative",
        "typing" => "Static",
        "execution" => "Interpreted",
        "file_extension" => ".sql",
        "popular_frameworks" => "MySQL, PostgreSQL",
        "used_for" => "Database queries",
        "why_use" => "Essential for data handling",
        "strengths" => "Powerful querying",
        "weaknesses" => "Not general-purpose",
        "database_support" => "All relational DB",
        "job_market" => "Very High",
        "learning_curve" => "Easy to Medium",
        "example_project" => "Database system",
    ],

    "html" => [
        "name" => "HTML (HyperText Markup Language)",
        "type" => "Markup",
        "first_release" => "1993",
        "creator" => "Tim Berners-Lee",
        "paradigm" => "Markup",
        "typing" => "N/A",
        "execution" => "Browser-rendered",
        "file_extension" => ".html",
        "popular_frameworks" => "None",
        "used_for" => "Web structure",
        "why_use" => "Foundation of web",
        "strengths" => "Simple",
        "weaknesses" => "Not programming language",
        "database_support" => "None",
        "job_market" => "Essential skill",
        "learning_curve" => "Easy",
        "example_project" => "Web page",
    ],

    "css" => [
        "name" => "CSS (Cascading Style Sheets)",
        "type" => "Styling",
        "first_release" => "1996",
        "creator" => "W3C",
        "paradigm" => "Style sheet",
        "typing" => "N/A",
        "execution" => "Browser-rendered",
        "file_extension" => ".css",
        "popular_frameworks" => "Tailwind, Bootstrap",
        "used_for" => "Styling UI",
        "why_use" => "Design websites",
        "strengths" => "Flexible design",
        "weaknesses" => "Can be messy",
        "database_support" => "None",
        "job_market" => "Essential skill",
        "learning_curve" => "Medium",
        "example_project" => "Styled website",
    ],

];

?>